[workspace]
resolver = "2"
members = ["host"]

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
ark-bn254       = { version = "0.5", default-features = false, features = ["curve"] }
ark-groth16     = { version = "0.5", default-features = false }
ark-ff          = { version = "0.5", default-features = false }
ark-ec          = { version = "0.5", default-features = false }
ark-serialize   = { version = "0.5", default-features = false }
ark-relations   = { version = "0.5", default-features = false }
ark-snark       = { version = "0.5", default-features = false }
ark-r1cs-std    = { version = "0.5", default-features = false }
ark-std         = { version = "0.5", default-features = false }
