[package]
name = "host"
version = "0.0.0"
edition.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "generate-vectors"
path = "src/generate_vectors.rs"

[dependencies]
ark-bn254 = { workspace = true, features = ["curve"] }
ark-groth16 = { workspace = true }
ark-ff = { workspace = true }
ark-ec = { workspace = true }
ark-serialize = { workspace = true }
ark-relations = { workspace = true }
ark-snark = { workspace = true }
ark-r1cs-std = { workspace = true }
ark-std = { workspace = true, features = ["std"] }
verifier-core = { path = "../script/crates/verifier-core" }
molecule = { version = "0.9", default-features = false, features = ["std"] }
groth16-schema = { path = "../script/crates/groth16-schema" }
ckb-hash = "1.1"

[dev-dependencies]
proptest = "1"
