[workspace]
resolver = "2"
members = ["crates/verifier-core", "crates/ckb-script", "crates/groth16-schema", "crates/wire-decode"]

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
ark-bn254 = { version = "0.5", default-features = false, features = ["curve"] }
ark-groth16 = { version = "0.5", default-features = false }
ark-ff = { version = "0.5", default-features = false }
ark-ec = { version = "0.5", default-features = false }
ark-serialize = { version = "0.5", default-features = false }
ark-relations = { version = "0.5", default-features = false }
ark-snark = { version = "0.5", default-features = false }

[profile.release]
overflow-checks = true
strip = true
codegen-units = 1
debug = false
opt-level = "z"
lto = true
panic = "abort"
